import { Product } from './models';
export const STORE = {
  hours: 'Terça a domingo, das 10h às 18h',
  address: 'Rua das Flores, 123 — São Paulo, SP (endereço demonstrativo)',
  deliveryFee: 800,
  cepMin: '01000000',
  cepMax: '05999999',
  interval: 15,
  openingHour: 10,
  closingHour: 18,
  closedWeekday: 1,
  promotion: { price: 2500, pairDiscount: 500 },
  socialUrl: '',
  supportUrl: '',
};
export const SAUCES = [
  { name: 'Sem calda', price: 0 },
  { name: 'Ninho', price: 300 },
  { name: 'Chocolate', price: 300 },
  { name: 'Caramelo', price: 300 },
];
export const PRODUCTS: Product[] = [
  {
    id: 'brigadeirao',
    name: 'Brigadeirão',
    description: 'Massa de chocolate, brigadeiro cremoso e uma generosa camada de carinho.',
    category: 'Chocolate',
    price: 2500,
    stock: 12,
    image: 'brigadeirao',
    tag: 'O queridinho',
  },
  {
    id: 'ninho',
    name: 'Ninho com Nutella',
    description: 'Massa fofinha, creme de leite Ninho e o encontro perfeito com Nutella.',
    category: 'Cremosos',
    price: 2500,
    stock: 8,
    image: 'ninho',
    tag: 'Irresistível',
  },
  {
    id: 'uva',
    name: 'Bombom de Uva',
    description: 'Uvas frescas envolvidas em creme branco, entre camadas bem macias.',
    category: 'Frutas',
    price: 2500,
    stock: 6,
    image: 'uva',
  },
  {
    id: 'morango',
    name: 'Morango com Chocolate',
    description: 'Morangos frescos e chocolate intenso. Uma combinação feita para apaixonar.',
    category: 'Frutas',
    price: 2500,
    stock: 9,
    image: 'morango',
    tag: 'Com fruta de verdade',
  },
  {
    id: 'doce',
    name: 'Doce de Leite',
    description: 'Camadas delicadas com doce de leite cremoso e sabor de abraço.',
    category: 'Cremosos',
    price: 2500,
    stock: 7,
    image: 'doce',
  },
  {
    id: 'abacaxi',
    name: 'Abacaxi com Coco',
    description: 'Abacaxi suculento, creme leve e coco para um toque tropical.',
    category: 'Frutas',
    price: 2500,
    stock: 5,
    image: 'abacaxi',
  },
  {
    id: 'prestigio',
    name: 'Prestígio',
    description: 'Chocolate macio e recheio generoso de coco. Um clássico artesanal.',
    category: 'Chocolate',
    price: 2500,
    stock: 0,
    image: 'prestigio',
  },
  {
    id: 'caramelo',
    name: 'Chocolate com Caramelo',
    description: 'Chocolate intenso e caramelo dourado com um delicado toque de sal.',
    category: 'Chocolate',
    price: 2500,
    stock: 10,
    image: 'caramelo',
  },
];
